// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_ota_control                     19
#define gattdb_environmental                   22
#define gattdb_acc_gyro_mag                    25
#define gattdb_accelerometer_events            28
#define gattdb_led_state                       31
#define gattdb_battery_status                  34
#define gattdb_smoke                           37
#define gattdb_temperature_alert               40
#define gattdb_adc                             43
#define gattdb_set_config                      47

#endif
